apiVersion: v1
kind: Service
metadata:
  name: argocd-example-app-service
spec:
  type: ClusterIP
  selector:
    app: argocd-example-app
  ports:
    - port: 8087
      targetPort: 80
      protocol: TCP
      #nodePort: 31000 # Optional: Kubernetes will choose a port if this is omitted
